### ISSUE TITLE
Explain vars

### ISSUE THREAD

**Issue by till** [linuxhq/ansible-role-elrepo#7]
There are lots of vars available and to be set. Can you explain what they all do?

**Comment by tkimball83** [comment]
Hello @till! 

I'm not going to document every variable listed in /defaults/ here in GitHub issues.  However, is there a specific variable that's causing confusion?  Hopefully I can assist if you're stuck.

Thanks!

**Comment by till** [comment]
Sure, so I figured out what a minimum playbook looks like:

```
- name: Install kernel-ml
  include_role:
    name: linuxhq.elrepo
  vars:
    elrepo_kernel: True
```

I haven't read the source, and I know I _could_ just thinking it would be nicer not having to read the role to see what everything does.

I think these two should not be "set-able", or maybe explain why this would be good:
 - `elrepo_dist`
 - `elrepo_version`

I kinda see the point with `elrepo_version`, but then again, I also don't. ;-)

I haven't looked yet at why I would need any of these:
```
elrepo_disable_plugin: []
elrepo_disablerepo: []
elrepo_enable_plugin: []
elrepo_enablerepo: []
```


These two are the the only I really need:
```
elrepo_kernel: false
elrepo_kernel_version: ml
```

Not sure about the rest:

```
elrepo_packages: []
elrepo_repository_elrepo: false
elrepo_repository_extras: false
elrepo_repository_kernel: false
elrepo_repository_testing: false
```

**Comment by tkimball83** [comment]
`elrepo_dist`

This is done to have a shorter variable, could be moved to vars/ as well.

`elrepo_version` - 

We need this dictionary to pull down the rpm due to the version differences between os releases.  This could be done in multiple tasks as well, but I think this is the cleaner solution.  If you have another solution, I'm open to suggestions!   

`elrepo_{enable,disable}{repo,_plugin}` -

Due to conflicts or dependencies, you may want to enable or disable another third party repo while this role executes.  As for the enable/disable plugin, see yum's post-transactions-actions plugin as an example, which allows scripts or commands to be executed after a yum transaction completes.  I use this in several locations, and may not want any actions to be taken during the elrepo role process. An example configuration below where the system would automagically reboot after a new elrepo kernel is applied, but I dont want it executed during an ansible run: 

```
$ sudo cat /etc/yum/post-actions/kernel-ml.action
kernel-ml:install:/usr/sbin/grub2-set-default 0 && /usr/bin/systemctl reboot
```

`elrepo_packages` -

This allows you to install other packages that elrepo provides, as they provide more than just kernels.  Package `kmod-tpe` is a great example for an additional layer of security.

`elrepo_repository_*` - 

This allows you to enable other elrepo repositories, not just the default.  Majority of users probably wont need this, however having the functionality is a nice to have, so why not include it?

**Comment by till** [comment]
@tkimball83 makes sense, and thanks for explaining. Should I add a table to your readme to explain this or do you want to do it?

**Comment by tkimball83** [comment]
@till - Go for it!  I'll await your pull request.

I'm going to close out this issue in the meantime.

Thanks!
